# Generated by Django 5.2.8 on 2025-11-18 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_group_location_latitude_group_location_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='location_latitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='location_longitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True),
        ),
    ]
