# Generated by Django 5.2.8 on 2025-11-19 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_group_location_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='is_revealed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='group',
            name='reveal_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
