# Generated by Django 5.2.8 on 2025-01-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_cookieconsent_pushsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='push_notifications_asked',
            field=models.BooleanField(default=False),
        ),
    ]

